export const config = {
  // Existing flags
  NOTIFICATIONS_BATCHING_ENABLED: process.env.NEXT_PUBLIC_NOTIFICATIONS_BATCHING_ENABLED === 'false' ? false : true,
  NOTIFICATIONS_REALTIME_ENABLED: process.env.NEXT_PUBLIC_NOTIFICATIONS_REALTIME_ENABLED === 'true',
  NOTIFICATIONS_TOASTS_ENABLED: process.env.NEXT_PUBLIC_NOTIFICATIONS_TOASTS_ENABLED === 'true',
  ANALYTICS_USE_MOCK: process.env.NEXT_PUBLIC_ANALYTICS_USE_MOCK === 'true',

  // New guardrail flags (default OFF)
  SERVER_NOTIFICATIONS_BATCHING_ENABLED:
    process.env.NEXT_PUBLIC_SERVER_NOTIFICATIONS_BATCHING_ENABLED === 'true' ||
    process.env.SERVER_NOTIFICATIONS_BATCHING_ENABLED === 'true' ||
    process.env.NOTIFICATIONS_SERVER_BATCHING_ENABLED === 'true' ||
    false,

  NOTIFICATIONS_SSE_ENABLED: process.env.NEXT_PUBLIC_NOTIFICATIONS_SSE_ENABLED === 'true',

  DELIVERY_EMAIL_ENABLED: process.env.NEXT_PUBLIC_DELIVERY_EMAIL_ENABLED === 'true',
  DELIVERY_PUSH_ENABLED: process.env.NEXT_PUBLIC_DELIVERY_PUSH_ENABLED === 'true',
  DELIVERY_WEBHOOK_ENABLED: process.env.NEXT_PUBLIC_DELIVERY_WEBHOOK_ENABLED === 'true',
}
